# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 06:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtUserDialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create date')),
                ('friend1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Friend1', to=settings.AUTH_USER_MODEL)),
                ('friend2', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Friend2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtUserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=50000, verbose_name='Message')),
                ('send_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Send date')),
                ('delivered', models.BooleanField(default=False, verbose_name='Delivered')),
                ('owner', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='extuserdialog',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='dialogs_messages', to='ExtUserCorrespondence.ExtUserMessage'),
        ),
    ]
