# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 12:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ExtUserCorrespondence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extuserdialog',
            name='friend1',
        ),
        migrations.RemoveField(
            model_name='extuserdialog',
            name='friend2',
        ),
        migrations.AddField(
            model_name='extuserdialog',
            name='friends',
            field=models.ManyToManyField(related_name='CorrespondenceSides', to=settings.AUTH_USER_MODEL),
        ),
    ]
