# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExtUser', '0003_extuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Admin'),
        ),
    ]
